apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: login-api
  name: login-api
spec:
  type: NodePort
  ports:
  - name: "5555"
    port: 5555
    targetPort: 8080
  selector:
    io.kompose.service: login-api
status:
  loadBalancer: {}
